### ISSUE TITLE
Empty body causes failure

### ISSUE THREAD

**Issue by Levi-Lesches** [Levi-Lesches/blocking-issues#12]
An empty body means `issue.body` is `null`, not `""`, which causes an error. The check should actually pass to indicate the PR is ready to merge.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i just wanted to point this out :)

**Comment by Levi-Lesches** [comment]
I was actually browsing your PRs to see how your tests were going when I noticed the failures. Wanted to see if I could beat you to it!

**Comment by Levi-Lesches** [comment]
Fixed in `v1.2.1`
