### ISSUE TITLE
Multiple blocking issues doesn't work

### ISSUE THREAD

**Issue by ezono-Muhammad** [Levi-Lesches/blocking-issues#2]
I mentioned 

blocked by #1 
blocked by #2

and it only checks for issue that is mentioned first. If I close #1 and #2 is still open, the bot doesn't recognize it and says we're good to merge

**Comment by Levi-Lesches** [comment]
Make sure you're using version 1.1 in your workflow file, as using version 1 won't update automatically

**Comment by ezono-Muhammad** [comment]
Suppose we've an issue **Feature bug**

it is blocked by 

**Bug 1**
**Bug 2**
**Bug 3**

Even if all three bugs open, we can close the **Feature Bug**. 

The idea should be that **Feature Bug** should not be closed until all bugs are fixed. But if someone by mistake closes **Feature Bug** then it should be reopened as it is still blocked by open issues.

**Comment by Levi-Lesches** [comment]
Many projects use closing issues/PRs as a way to say "this idea is no longer being considered", which has nothing to do with whether it was blocked or not. Besides, it's not a good idea for a bot to override a manual user action -- then there would be no way to close an issue/PR.
