### ISSUE TITLE
License of this tool?

### ISSUE THREAD

**Issue by weikengchen** [Levi-Lesches/blocking-issues#24]
I am looking for a tool that extracts "blocked by" in PRs and are able to provide auxiliary functionalities, such as showing a chain, or a circle, of the blocking relationships between the different repos and the involved PRs.

I wonder if you have decided a license for your tool. 

And you can register for GitHub sponsorship so people who use this tool can support you back: https://github.com/sponsors

**Comment by Levi-Lesches** [comment]
Good question! I just added the LICENSE file, it's the MIT license. I just want something that keeps my copyright but allows for using the action in any type of project with any modifications. I do not require that changes be merged upstream, that's too much IMO, but if you add any generally useful features, I'd appreciate a PR so others could benefit from it. 

Thanks for the sponsorship suggestion; I'm looking into setting that up.

If you need any help, feel free to ask here, I probably did not document this tool as well as I could have. The [GitHub Actions docs](https://docs.github.com/en/actions) are also pretty useful, along with the [REST API](https://docs.github.com/en/rest) (and the [Octokit docs](https://octokit.github.io/rest.js/v18/) as well).

**Comment by weikengchen** [comment]
Thanks. I will try it a bit. As you can see, there is a real use case.
As a debugger, I am generally desperate enough to not read the documentation...
