### ISSUE TITLE
⬆️ Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by ebouchut** [Levi-Lesches/blocking-issues#26]
👍 Thank you for this useful action.

## Node.js 16 Actions are Deprecated

I get [this error](https://github.com/ebouchut/trio-docs/actions/runs/11516408147) when running [a workflow](https://github.com/ebouchut/trio-docs/blob/379ddbf355caaddf92e6dfbb0df384d2f86c39f1/.github/workflows/check_blocking_prs_and_issues.yml) using the `Levi-Lesches/blocking-issues` action.

> The following actions use a deprecated Node.js version and will be forced to run on node20: Levi-Lesches/blocking-issues@v2.  
> For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

If fixing this issue requires bumping the Node.js version number in [this line](https://github.com/Levi-Lesches/blocking-issues/blob/9fd381f401cc66cfd361a179bdf4770646d824c6/action.yml#L16), I opened PR #27 with what I guess should be the start of a fix.

**Comment by Levi-Lesches** [comment]
Ah, thanks for notifying me. It was in fact as simple as that, and from what I can tell there should be no relevant breaking changes. However, I did add some more error-handling logic (in the case that the bot tries to unblock an issue that wasn't blocked), so unfortunately I'll need to do more than just merge your PR. But I did use it as a starting point, and included your commit in #28 so you're included as a co-author. 

You can see the new [workflow run](https://github.com/Levi-Lesches/blocking-issues-test/actions/runs/11543181874) that doesn't fail or give deprecation warnings for [this PR](https://github.com/Levi-Lesches/blocking-issues-test/pull/25). Thanks again!
