### ISSUE TITLE
Replace labels with a `use-label` parameter to use an existing label

### ISSUE THREAD

**Issue by Levi-Lesches** [Levi-Lesches/blocking-issues#7]
There are currently individual options for a label's name, color, and description. Changing any of these values after the workflow has been deployed may result in inconsistent behavior as the bot may fail to find issues with the old label. 

Instead, the workflow should only accept the label's name to apply. If users want to change anything about the label, they can do so in the GitHub UI and change the name in the workflow file. This change eliminates any issues when changing the color or description. When changing the label's name, GitHub will automatically rename any issues/PRs with the label to use the new name, and the workflow can then use the new name only.

**Note**: This will be a breaking change from `v1.2`.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Sorry to add more clutter here; I think I may do #7 instead, which would be a breaking change if you use the new options. With that approach, instead of providing the options to the workflow file, you would make the label yourself, along with its color and description, and then use the `use-label` option to direct the workflow to that label. That makes the workflow more resistant to changes to the label, such as description, color, and name (you would make those changes in the GitHub UI instead).

@Levi-Lesches lets take it to here :)
This solution is actually a way better approach.

**Comment by Levi-Lesches** [comment]
Fixed by #18, use `v2` (or `v2.0.0` specifically) for this new feature.
